spring:
  profiles:
    # 默认激活 dev 环境
    active: dev
#  jackson:
#    # 设置后台返参，若字段值为 null, 则不返回
##    default-property-inclusion: non_null
#    # 设置日期字段格式
#    date-format: yyyy-MM-dd HH:mm:ss

jwt:
  #  签发人
  issuer: quanxiaoha
  secret: XpLopnbOjJFnxQS6aAuzB9ZhmUJAeGq7NZT1fEw0p4tscoE0IDhkUn0VCgckouN7FYo8GQ8eLH/5EGh/T3KGgA==
